/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timing_packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "timing_packet.pb-c.h"
void   aero_network__timing_packet__init
                     (AeroNetwork__TimingPacket         *message)
{
  static AeroNetwork__TimingPacket init_value = AERO_NETWORK__TIMING_PACKET__INIT;
  *message = init_value;
}
size_t aero_network__timing_packet__get_packed_size
                     (const AeroNetwork__TimingPacket *message)
{
  assert(message->base.descriptor == &aero_network__timing_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t aero_network__timing_packet__pack
                     (const AeroNetwork__TimingPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &aero_network__timing_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t aero_network__timing_packet__pack_to_buffer
                     (const AeroNetwork__TimingPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &aero_network__timing_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AeroNetwork__TimingPacket *
       aero_network__timing_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AeroNetwork__TimingPacket *)
     protobuf_c_message_unpack (&aero_network__timing_packet__descriptor,
                                allocator, len, data);
}
void   aero_network__timing_packet__free_unpacked
                     (AeroNetwork__TimingPacket *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &aero_network__timing_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor aero_network__timing_packet__field_descriptors[5] =
{
  {
    "mac_address",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(AeroNetwork__TimingPacket, mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset_from_master_s",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AeroNetwork__TimingPacket, offset_from_master_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset_from_master_ns",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AeroNetwork__TimingPacket, offset_from_master_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mean_path_delay_s",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AeroNetwork__TimingPacket, mean_path_delay_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mean_path_delay_ns",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AeroNetwork__TimingPacket, mean_path_delay_ns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned aero_network__timing_packet__field_indices_by_name[] = {
  0,   /* field[0] = mac_address */
  4,   /* field[4] = mean_path_delay_ns */
  3,   /* field[3] = mean_path_delay_s */
  2,   /* field[2] = offset_from_master_ns */
  1,   /* field[1] = offset_from_master_s */
};
static const ProtobufCIntRange aero_network__timing_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor aero_network__timing_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "aero_network.timing_packet",
  "TimingPacket",
  "AeroNetwork__TimingPacket",
  "aero_network",
  sizeof(AeroNetwork__TimingPacket),
  5,
  aero_network__timing_packet__field_descriptors,
  aero_network__timing_packet__field_indices_by_name,
  1,  aero_network__timing_packet__number_ranges,
  (ProtobufCMessageInit) aero_network__timing_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
