/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: timing_packet.proto */

#ifndef PROTOBUF_C_timing_5fpacket_2eproto__INCLUDED
#define PROTOBUF_C_timing_5fpacket_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _AeroNetwork__TimingPacket AeroNetwork__TimingPacket;


/* --- enums --- */


/* --- messages --- */

struct  _AeroNetwork__TimingPacket
{
  ProtobufCMessage base;
  int64_t mac_address;
  int32_t offset_from_master_s;
  int32_t offset_from_master_ns;
  int32_t mean_path_delay_s;
  int32_t mean_path_delay_ns;
};
#define AERO_NETWORK__TIMING_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&aero_network__timing_packet__descriptor) \
    , 0, 0, 0, 0, 0 }


/* AeroNetwork__TimingPacket methods */
void   aero_network__timing_packet__init
                     (AeroNetwork__TimingPacket         *message);
size_t aero_network__timing_packet__get_packed_size
                     (const AeroNetwork__TimingPacket   *message);
size_t aero_network__timing_packet__pack
                     (const AeroNetwork__TimingPacket   *message,
                      uint8_t             *out);
size_t aero_network__timing_packet__pack_to_buffer
                     (const AeroNetwork__TimingPacket   *message,
                      ProtobufCBuffer     *buffer);
AeroNetwork__TimingPacket *
       aero_network__timing_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   aero_network__timing_packet__free_unpacked
                     (AeroNetwork__TimingPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*AeroNetwork__TimingPacket_Closure)
                 (const AeroNetwork__TimingPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor aero_network__timing_packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_timing_5fpacket_2eproto__INCLUDED */
